exp_name: "ppo_continuous"
seed: 1
torch_deterministic: true
cuda: True
capture_video: False
save_model: True
bc_init: True

env_id: "MountainCarContinuous-v0"
total_timesteps: 1000000
learning_rate: 0.0003
num_envs: 10
num_steps: 1024 #2048
anneal_lr: True
gamma: 0.97
gae_lambda: 0.9 #0.95
num_minibatches: 32
update_epochs: 5 #10
norm_adv: True
clip_coef: 0.1 # 0.2
clip_vloss: True
ent_coef: 0.1
vf_coef: 0.2 #0.5
max_grad_norm: 0.5
target_kl: 0.02 #null  # YAML's equivalent of None
save_interval: 100